#Application Browser
browser=edge
#Application url
url=https://www.demoblaze.com/
#User Credential
username=QAUser1
password=12345678
name=Nasrin
country=India
city=Chennai
creditcard=7473 2343 2334
month=December


